// src/connection/connection.hpp
#pragma once

#include "drivers/driver_configs.hpp"
#include "drivers/driver_interface.hpp"

#include <QByteArray>
#include <QObject>
#include <QString>
#include <chrono>
#include <memory>
#include <optional>
#include <variant>
#include <vector>

namespace signalforge::connection {

/// Driver type discriminator for `ConnectionConfig::driverConfig`.
///
/// Numeric values are explicit for log + yaml stability. The
/// yaml-side spelling is the lower-case enumerator name (`serial`,
/// `tcp`, `udp`, `replay`).
///
/// Frozen at M9 close.
enum class DriverType : int {
    Serial = 0,
    Tcp = 1,
    Udp = 2,
    Replay = 3,
};

/// One auto-connect command sent after a `Connection` enters the
/// Connected state. Sequential per spec §3.5; failures log and
/// continue without disconnecting the parent connection.
///
/// `payload` is a raw byte buffer (NUL and CRLF survive the yaml
/// round-trip via `!!binary` base64 encoding). When `expected` is
/// set, the driver waits up to `timeout` for a matching response.
/// `delayBefore` is honored before the payload is written.
///
/// Frozen at M9 close.
struct AutoConnectCommand {
    QString name;
    QByteArray payload;
    std::optional<QByteArray> expected;
    std::chrono::milliseconds timeout{1000};
    std::chrono::milliseconds delayBefore{0};
};

/// Driver-specific configuration variant. M9 reuses the M3
/// `signalforge::drivers::*Config` types directly (M9-concerns.md
/// C1) instead of declaring duplicate structs in this namespace.
///
/// Frozen at M9 close: the variant alternatives and ordering.
using DriverConfig = std::variant<signalforge::drivers::SerialConfig, signalforge::drivers::TcpConfig,
                                  signalforge::drivers::UdpConfig, signalforge::drivers::ReplayConfig>;

/// User-facing configuration for a single connection.
///
/// `id` is auto-generated by `ConnectionManager::addConnection` if
/// empty. `displayName` is shown in the connection list. The
/// `driverType` field is the runtime tag for `driverConfig`; the
/// two must agree (validated by `Connection::Connection`).
///
/// `decoderSchemaId` references an M5 schema (resolved at
/// connect-time via the `DecoderRegistrar` configured in
/// `MainWindow`).
///
/// `autoConnectOnStartup` is **forward-compatibility only** in V1;
/// per design decision M9.2 the V1 reconnect behavior is manual
/// (see `docs/milestones/M9-connection-manager.md` §3.2).
///
/// Frozen at M9 close: field set + names + default values.
struct ConnectionConfig {
    QString id;
    QString displayName;
    DriverType driverType = DriverType::Serial;
    DriverConfig driverConfig{};
    QString decoderSchemaId;
    bool autoConnectOnStartup = false;
    std::vector<AutoConnectCommand> autoConnectCommands;
};

/// One driver wrapped in a manager-coordinated lifecycle state
/// machine. Owned by `ConnectionManager`.
///
/// State machine (per spec §4.4):
/// ```
/// Idle ─connectDriver()─▶ Connecting ─driver Open─▶ Connected
///   ▲                         │                         │
///   │                         │ driver Error            │ disconnectDriver()
///   │                         ▼                         ▼
///   └── disconnectDriver() ─ Error ◀── runtime err ─ Disconnecting
///                                                        │
///                                                        └─▶ Idle
/// ```
///
/// Threading: lives on the main thread. The owned driver may run
/// IO on a background thread (per M3 driver topology); state
/// transitions and signals are coalesced on the main thread.
///
/// Freeze scope: this class, its `State` enum, signals, and
/// public method set are frozen at M9 close.
class Connection : public QObject {
    Q_OBJECT
    Q_DISABLE_COPY_MOVE(Connection)

public:
    /// Lifecycle states. Numeric values explicit for log /
    /// metatype stability.
    enum class State : int {
        Idle = 0,           ///< Not yet connected; ready to connect
        Connecting = 1,     ///< connectDriver() in progress
        Connected = 2,      ///< Driver Running; data flowing
        Disconnecting = 3,  ///< disconnectDriver() in progress
        Error = 4,          ///< Terminal until disconnectDriver() resets to Idle
    };
    Q_ENUM(State)

    /// Build a connection from `config`. Constructs the
    /// underlying M3 driver from `config.driverConfig`. The
    /// connection enters `Idle`; no IO is attempted until
    /// `connectDriver()` is invoked.
    explicit Connection(ConnectionConfig config, QObject* parent = nullptr);
    ~Connection() override;

    /// Initiate the Idle/Error → Connecting → Connected sequence.
    /// Returns `false` if not in Idle or Error.
    [[nodiscard]] bool connectDriver();

    /// Initiate the Connected/Connecting/Error → Disconnecting →
    /// Idle sequence. Returns `false` if already Idle.
    [[nodiscard]] bool disconnectDriver();

    /// Current state.
    [[nodiscard]] State state() const noexcept;

    /// Last error message (empty if state never reached Error).
    [[nodiscard]] const QString& lastError() const noexcept;

    /// Current configuration.
    [[nodiscard]] const ConnectionConfig& config() const noexcept;

    /// Underlying M3 driver. Non-null after construction.
    /// Lifetime tied to the `Connection`.
    [[nodiscard]] signalforge::drivers::DriverInterface* driver() const noexcept;

    /// Replace the configuration. Only succeeds in Idle.
    /// On success rebuilds the underlying driver to match the new
    /// `driverConfig`.
    [[nodiscard]] bool setConfig(const ConnectionConfig& newConfig);

signals:
    /// Emitted on every state transition, on the main thread.
    void stateChanged(signalforge::connection::Connection::State newState);

    /// Emitted when the driver reports an error. The connection
    /// also transitions to `Error` if not already there.
    void errorOccurred(const QString& errorMessage);

    /// Emitted as each auto-connect command is dispatched (S7).
    void autoConnectCommandSent(const QString& commandName);

    /// Emitted when the auto-connect sequence finishes. `success`
    /// is `true` only if every command completed without error
    /// (timeouts on `expected` count as success per spec §3.5).
    void autoConnectCompleted(bool success);

private:
    void rebuildDriver();
    void wireDriverSignals();
    void setState(State next);
    void setError(const QString& message);

    void onDriverState(signalforge::drivers::DriverState driverState);
    void onDriverError(signalforge::drivers::DriverError error);

    ConnectionConfig config_;
    std::unique_ptr<signalforge::drivers::DriverInterface> driver_;
    State state_ = State::Idle;
    QString lastError_;
};

}  // namespace signalforge::connection

Q_DECLARE_METATYPE(signalforge::connection::Connection::State)
